### ISSUE TITLE
Licensing? Can I use sources for derivative projects? 

### ISSUE THREAD

**Issue by nihirash** [UzixLS/zx-midiplayer#1]
Hi!

Can I use your SMF-parser and all basic player code for making my players/plugins for esxDOS browser/wild commander plugin etc? 

What limitation should I respect?

**Comment by UzixLS** [comment]
Isn't defined currently, probably would be GPL

**Comment by UzixLS** [comment]
Licensed under GPLv3
cfd10bb232fc167a63c8f526a25c6c4de7cbf7bf
